# Generated by Django 3.2.12 on 2022-02-21 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='demo1',
            new_name='demo2',
        ),
    ]
